apiVersion: v1
kind: ConfigMap
metadata:
  name: artemis-broker-logging-config
data:
  logging.properties: |
    monitorInterval = 5
    rootLogger.level={{ .Values.logging.level.root }}
    rootLogger.appenderRef.console.ref = console
    logger.activemq.name=org.apache.activemq
    logger.activemq.level={{ .Values.logging.level.activemq }}
    logger.artemis_server.name=org.apache.activemq.artemis.core.server
    logger.artemis_server.level={{ .Values.logging.level.server }}
    logger.artemis_journal.name=org.apache.activemq.artemis.journal
    logger.artemis_journal.level={{ .Values.logging.level.journal }}
    logger.artemis_utils.name=org.apache.activemq.artemis.utils
    logger.artemis_utils.level={{ .Values.logging.level.utils }}
    # audit logging levels
    logger.audit_base.name = org.apache.activemq.audit.base
    logger.audit_base.additivity = false
    logger.audit_base = DEBUG, console
    logger.audit_resource.name = org.apache.activemq.audit.resource
    logger.audit_resource.additivity = false
    logger.audit_resource = OFF, console
    logger.audit_message.name = org.apache.activemq.audit.message
    logger.audit_message.additivity = false
    logger.audit_message = OFF, console
      # CriticalAnalyzer: If you have issues with the CriticalAnalyzer, setting this to TRACE would give
      # you extra troubleshooting info, but do not use TRACE regularly as it would incur extra CPU usage.
    logger.critical_analyzer.name=org.apache.activemq.artemis.utils.critical
    logger.critical_analyzer.level=ERROR
      # Jetty logger levels
    logger.jetty.name=org.eclipse.jetty
    logger.jetty.level=WARN
      # web console authenticator too verbose for impatient client
    logger.authentication_filter.name=io.hawt.web.auth.AuthenticationFilter
    logger.authentication_filter.level={{ .Values.logging.level.authentication }}
      # Quorum related logger levels
    logger.curator.name=org.apache.curator
    logger.curator.level=WARN
    logger.zookeeper.name=org.apache.zookeeper
    logger.zookeeper.level=ERROR
      # Console appender
    appender.console.type=Console
    appender.console.name=console
    appender.console.layout.type=PatternLayout
    appender.console.layout.pattern=%d %-5level [%logger] %msg%n
