apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker-tls
spec:
  acceptors:
    - name: "artemis"
      port: 62627
      protocols: core
      sslEnabled: true
      sslSecret: {{ .Values.secrets.acceptor.secretName }}
  addressSettings:
  adminUser: {{ .Values.secrets.admin.user }}
  adminPassword: {{ .Values.secrets.admin.password }}
  brokerProperties:
    - globalMaxSize=512m
  connectors:
    - name: 'rmi'
      host: 0.0.0.0
      port: 1099
      expose: true
      ingressHost: '192.168.205.9'
  console:
    expose: true
    ingressHost: {{ .Values.ingress.host }}
  deploymentPlan:
    affinity:
    annotations:
    clustered: true
    enableMetricsPlugin: true
    extraMounts:
      configMaps:
      secrets:
    image: {{ .Values.broker.image }}
    imagePullSecrets:
      - name: 'xibus-harbor'
    initImage: {{ .Values.broker.initImage }}
    jolokiaAgentEnabled: true
    journalType: AIO
    labels:
    {{- if .Values.broker.livenessProbe }}
    {{- with .Values.broker.livenessProbe -}}
    livenessProbe:
    {{- toYaml . | nindent 6 }}
    {{ end -}}
    {{- end -}}
    managementRBACEnabled:
    messageMigration: true
    nodeSelector:
    persistenceEnabled: true
    podDisruptionBudget:
      minAvailable: 1
    podSecurity:
    podSecurityContext:
      fsGroup: 0
      fsGroupChangePolicy: 'OnRootMismatch'
    {{ if .Values.broker.readinessProbe }}
    {{- with .Values.broker.readinessProbe -}}
    readinessProbe:
    {{- toYaml . | nindent 6 }}
    {{ end -}}
    {{- end -}}
    requireLogin: false
    {{- if .Values.broker.resources }}
    {{- with .Values.broker.resources }}
    resources:
    {{- toYaml . | nindent 6 }}
    {{ end -}}
    {{ end -}}
    size: {{ .Values.broker.replicas }}
    startupProbe:
    {{- if .Values.broker.storage }}
    {{- with .Values.broker.storage -}}
    storage:
    {{- toYaml . | nindent 6 }}
    {{ end -}}
    {{- end -}}
    tolerations:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - xibus-artemis
  env:
    - name: ARGS
      value: "--zap-log-level=debug"
    - name: RUN_BROKER
      value: 'true'
    - name: CONFIG_BROKER
      value: 'true'
    {{ if .Values.broker.extraEnv }}
    {{- range $val := .Values.broker.extraEnv -}}
    - name: {{ $val.name }}
      value: {{ $val.value }}
    {{- end -}}
    {{- end }}
  upgrades:
    enabled: false
    minor: false
