{{ if .Values.service.main.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    application: xibus-artemis
  name: artemis-console-0
spec:
  ports:
    - port: 8161
      protocol: TCP
      targetPort: 8161
      name: console
  selector:
    application: xibus-artemis
                 artemis-broker-ss-0
{{- end -}}
---
